services:

  web:
    image: dementievnet/nginx:latest
    container_name: nginx
    working_dir: /etc/nginx
    volumes:
      - ./app:/app
      - ./config/nginx:/etc/nginx/conf.d
      - ./app/log/nginx:/var/log/nginx/
    ports:
      - "80:80"
      - "443:443"
    restart: always
    depends_on:
      - php
      - db

  php:
    build:
      context: ./config/php
      dockerfile: Dockerfile
    image: dementievnet/php:latest
    container_name: php
    working_dir: /app/www
    volumes:
      - ./app:/app
      - ./config/php/php-ini-overrides.ini:/usr/local/etc/php/conf.d/00-php.ini
      - ./bin/sendmail:/usr/local/bin/sendmail
    restart: always
    environment:
      PHP_IDE_CONFIG: serverName=localhost

  db:
    image: dementievnet/mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./app/db:/var/lib/mysql
      - ./app/log/mysql:/var/log/mysql/
      - ./config/mysql/conf.d:/etc/mysql/conf.d
    ports:
      - "3306:3306"
    restart: always

  phpmyadmin:
    image: dementievnet/phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      - PMA_ARBITRARY=1
    restart: always
    ports:
      - 8081:80
    environment:
      PMA_HOST: db
